Meteor.startup(function() {
	return Meteor.methods({
		resetAllCompany: function() {
			Company.remove({});
			Company.insert({company: "--Nova empresa--"});
		},
		resetAllCollections: function() {
			Company.remove({});
			Company.insert({company: ""});
			Company.insert({company: "--Nova empresa--"});

			Relation.remove({});
		},
		initCompanyCollection: function() {
			Company.insert({company: "3WT", index: "3WT".toLowerCase()});
			Company.insert({company: "8d digital", index: "8d digital".toLowerCase()});
			Company.insert({company: "Ablevision", index: "Ablevision".toLowerCase()});
			Company.insert({company: "Accenture", index: "Accenture".toLowerCase()});
			Company.insert({company: "Amdocs", index: "Amdocs".toLowerCase()});
			Company.insert({company: "Aptor", index: "Aptor".toLowerCase()});
			Company.insert({company: "Arvinmeritor", index: "Arvinmeritor".toLowerCase()});
			Company.insert({company: "ATeCH", index: "ATeCH".toLowerCase()});
			Company.insert({company: "Atenatec", index: "Atenatec".toLowerCase()});
			Company.insert({company: "Atos origin", index: "Atos origin".toLowerCase()});
			Company.insert({company: "Autbank", index: "Autbank".toLowerCase()});
			Company.insert({company: "Avon", index: "Avon".toLowerCase()});
			Company.insert({company: "Axoon", index: "Axoon".toLowerCase()});
			Company.insert({company: "Claro", index: "Claro".toLowerCase()});
			Company.insert({company: "Bm&F", index: "Bm&F".toLowerCase()});
			Company.insert({company: "Bosch", index: "Bosch".toLowerCase()});
			Company.insert({company: "Bull", index: "Bull".toLowerCase()});
			Company.insert({company: "Ci&T", index: "Ci&T".toLowerCase()});
			Company.insert({company: "Conectiva", index: "Conectiva".toLowerCase()});
			Company.insert({company: "Consulte TI", index: "Consulte TI".toLowerCase()});
			Company.insert({company: "Contern", index: "Contern".toLowerCase()});
			Company.insert({company: "Coss Consulting", index: "Coss Consulting".toLowerCase()});
			Company.insert({company: "CPm Braxis", index: "CPm Braxis".toLowerCase()});
			Company.insert({company: "CPqd", index: "CPqd".toLowerCase()});
			Company.insert({company: "Banco Credit suisse", index: "Banco Credit suisse".toLowerCase()});
			Company.insert({company: "Banco Itaú", index: "Banco Itaú".toLowerCase()});
			Company.insert({company: "Banco santander", index: "Banco santander".toLowerCase()});
			Company.insert({company: "daitanlabs", index: "daitanlabs".toLowerCase()});
			Company.insert({company: "danone", index: "danone".toLowerCase()});
			Company.insert({company: "data solutions", index: "data solutions".toLowerCase()});
			Company.insert({company: "Philips", index: "Philips".toLowerCase()});
			Company.insert({company: "dmr Consulting", index: "dmr Consulting".toLowerCase()});
			Company.insert({company: "doois Tecnologia", index: "doois Tecnologia".toLowerCase()});
			Company.insert({company: "easy software", index: "easy software".toLowerCase()});
			Company.insert({company: "ergo&Ação", index: "ergo&Ação".toLowerCase()});
			Company.insert({company: "elektro", index: "elektro".toLowerCase()});
			Company.insert({company: "embrapa", index: "embrapa".toLowerCase()});
			Company.insert({company: "enalta", index: "enalta".toLowerCase()});
			Company.insert({company: "enjoy", index: "enjoy".toLowerCase()});
			Company.insert({company: "everis", index: "everis".toLowerCase()});
			Company.insert({company: "eyetec", index: "eyetec".toLowerCase()});
			Company.insert({company: "FAI", index: "FAI".toLowerCase()});
			Company.insert({company: "FacTI", index: "FacTI".toLowerCase()});
			Company.insert({company: "FBm Brasil", index: "FBm Brasil".toLowerCase()});
			Company.insert({company: "Freeddom ", index: "Freeddom ".toLowerCase()});
			Company.insert({company: "Freios rodoviários", index: "Freios rodoviários".toLowerCase()});
			Company.insert({company: "H.m.sandres", index: "H.m.sandres".toLowerCase()});
			Company.insert({company: "IBm", index: "IBm".toLowerCase()});
			Company.insert({company: "Ícaro", index: "Ícaro".toLowerCase()});
			Company.insert({company: "imAX Games", index: "imAX Games".toLowerCase()});
			Company.insert({company: "Indusoft", index: "Indusoft".toLowerCase()});
			Company.insert({company: "Integris", index: "Integris".toLowerCase()});
			Company.insert({company: "Instituto eldorado", index: "Instituto eldorado".toLowerCase()});
			Company.insert({company: "Itautec", index: "Itautec".toLowerCase()});
			Company.insert({company: "Itera Inovação", index: "Itera Inovação".toLowerCase()});
			Company.insert({company: "Iteris", index: "Iteris".toLowerCase()});
			Company.insert({company: "Johnson & Johnson", index: "Johnson & Johnson".toLowerCase()});
			Company.insert({company: "linkway", index: "linkway".toLowerCase()});
			Company.insert({company: "lnls - luz síncrotron", index: "lnls - luz síncrotron".toLowerCase()});
			Company.insert({company: "luz engenharia", index: "luz engenharia".toLowerCase()});
			Company.insert({company: "mC1 TI", index: "mC1 TI".toLowerCase()});
			Company.insert({company: "mds Inform.", index: "mds Inform.".toLowerCase()});
			Company.insert({company: "merial", index: "merial".toLowerCase()});
			Company.insert({company: "microsoft", index: "microsoft".toLowerCase()});
			Company.insert({company: "motorola", index: "motorola".toLowerCase()});
			Company.insert({company: "multicorpos", index: "multicorpos".toLowerCase()});
			Company.insert({company: "oracle", index: "oracle".toLowerCase()});
			Company.insert({company: "PadTec", index: "PadTec".toLowerCase()});
			Company.insert({company: "Paggo", index: "Paggo".toLowerCase()});
			Company.insert({company: "Phisystems", index: "Phisystems".toLowerCase()});
			Company.insert({company: "Pinuts studios", index: "Pinuts studios".toLowerCase()});
			Company.insert({company: "Portugal Telecom", index: "Portugal Telecom".toLowerCase()});
			Company.insert({company: "Pref são Carlos", index: "Pref são Carlos".toLowerCase()});
			Company.insert({company: "Pro IT", index: "Pro IT".toLowerCase()});
			Company.insert({company: "Primeup", index: "Primeup".toLowerCase()});
			Company.insert({company: "Promon logicalis", index: "Promon logicalis".toLowerCase()});
			Company.insert({company: "PTls", index: "PTls".toLowerCase()});
			Company.insert({company: "rA Catering", index: "rA Catering".toLowerCase()});
			Company.insert({company: "rede PrePag", index: "rede PrePag".toLowerCase()});
			Company.insert({company: "royal Canin", index: "royal Canin".toLowerCase()});
			Company.insert({company: "rhodia", index: "rhodia".toLowerCase()});
			Company.insert({company: "s&V Consultoria", index: "s&V Consultoria".toLowerCase()});
			Company.insert({company: "siemens", index: "siemens".toLowerCase()});
			Company.insert({company: "siena ", index: "siena ".toLowerCase()});
			Company.insert({company: "senior solution", index: "senior solution".toLowerCase()});
			Company.insert({company: "simula", index: "simula".toLowerCase()});
			Company.insert({company: "sIsGrAPH", index: "sIsGrAPH".toLowerCase()});
			Company.insert({company: "solução Integrada", index: "solução Integrada".toLowerCase()});
			Company.insert({company: "sYm Tecnologia", index: "sYm Tecnologia".toLowerCase()});
			Company.insert({company: "Talent Pro IT", index: "Talent Pro IT".toLowerCase()});
			Company.insert({company: "Tecumseh", index: "Tecumseh".toLowerCase()});
			Company.insert({company: "Telefonica", index: "Telefonica".toLowerCase()});
			Company.insert({company: "Trópicos", index: "Trópicos".toLowerCase()});
			Company.insert({company: "Trust Agro", index: "Trust Agro".toLowerCase()});
			Company.insert({company: "uCube", index: "uCube".toLowerCase()});
			Company.insert({company: "ultragaz", index: "ultragaz".toLowerCase()});
			Company.insert({company: "unesp", index: "unesp".toLowerCase()});
			Company.insert({company: "unilever", index: "unilever".toLowerCase()});
			Company.insert({company: "uol", index: "uol".toLowerCase()});
			Company.insert({company: "Verdartis", index: "Verdartis".toLowerCase()});
			Company.insert({company: "Vertis", index: "Vertis".toLowerCase()});
			Company.insert({company: "Whirlpool", index: "Whirlpool".toLowerCase()});
			Company.insert({company: "Vectura", index: "Vectura".toLowerCase()});
			Company.insert({company: "Yordan", index: "Yordan".toLowerCase()});
			Company.insert({company: "Zarpsystem", index: "Zarpsystem".toLowerCase()});
		},
		addCompanyNumber: function(company, country) {
			if (Company.find({index: company.toLowerCase()}).count() == 0) {
				Company.insert({company: company, index: company.toLowerCase()});
			};
			if (Relation.find({index: company.toLowerCase(), country: country}).count() == 0) {
				Relation.insert({company: company, country: country, quantity: 1, index: company.toLowerCase()});
			} else{
				Relation.update({index:company.toLowerCase(),country:country},
					{ $inc: {quantity: 1}});
			};
		},
		initCountryCollection: function() {
			Country.insert({students:"0",name:"Afeganistão"});
			Country.insert({students:"0",name:"Albânia"});
			Country.insert({students:"0",name:"Argélia"});
			Country.insert({students:"0",name:"Samoa"});
			Country.insert({students:"0",name:"Andorra"});
			Country.insert({students:"0",name:"Angola"});
			Country.insert({students:"0",name:"Antígua e Barbuda"});
			Country.insert({students:"0",name:"Azerbaijão"});
			Country.insert({students:"0",name:"Argentina"});
			Country.insert({students:"0",name:"Austrália"});
			Country.insert({students:"0",name:"Áustria"});
			Country.insert({students:"0",name:"Bahamas"});
			Country.insert({students:"0",name:"Barém"});
			Country.insert({students:"0",name:"Bangladeche"});
			Country.insert({students:"0",name:"Armenia"});
			Country.insert({students:"0",name:"Barbados"});
			Country.insert({students:"0",name:"Bélgica"});
			Country.insert({students:"0",name:"Bermudas"});
			Country.insert({students:"0",name:"Butão"});
			Country.insert({students:"0",name:"Bolívia"});
			Country.insert({students:"0",name:"Bósnia e Herzegovina"});
			Country.insert({students:"0",name:"Botsuana"});
			Country.insert({students:"0",name:"Ilha Bouvet"});
			Country.insert({students:"0",name:"Brasil"});
			Country.insert({students:"0",name:"Belize"});
			Country.insert({students:"0",name:"Ilhas Salomão"});
			Country.insert({students:"0",name:"Ilhas Virgens Britânicas"});
			Country.insert({students:"0",name:"Brunei"});
			Country.insert({students:"0",name:"Bulgária"});
			Country.insert({students:"0",name:"Birmânia"});
			Country.insert({students:"0",name:"Burúndi"});
			Country.insert({students:"0",name:"Bielorrússia"});
			Country.insert({students:"0",name:"Camboja"});
			Country.insert({students:"0",name:"Camarões"});
			Country.insert({students:"0",name:"Canadá"});
			Country.insert({students:"0",name:"Cabo Verde"});
			Country.insert({students:"0",name:"Ilhas Caimão"});
			Country.insert({students:"0",name:"República Centro-Africana"});
			Country.insert({students:"0",name:"Sri Lanca"});
			Country.insert({students:"0",name:"Chade"});
			Country.insert({students:"0",name:"Chile"});
			Country.insert({students:"0",name:"China"});
			Country.insert({students:"0",name:"Taiwan"});
			Country.insert({students:"0",name:"Ilha do Natal"});
			Country.insert({students:"0",name:"Colômbia"});
			Country.insert({students:"0",name:"Comores"});
			Country.insert({students:"0",name:"Mayotte"});
			Country.insert({students:"0",name:"Congo-Brazzaville"});
			Country.insert({students:"0",name:"Congo-Kinshasa"});
			Country.insert({students:"0",name:"Ilhas Cook"});
			Country.insert({students:"0",name:"Costa Rica"});
			Country.insert({students:"0",name:"Croácia"});
			Country.insert({students:"0",name:"Cuba"});
			Country.insert({students:"0",name:"Chipre"});
			Country.insert({students:"0",name:"República Checa"});
			Country.insert({students:"0",name:"Benim"});
			Country.insert({students:"0",name:"Dinamarca"});
			Country.insert({students:"0",name:"Domínica"});
			Country.insert({students:"0",name:"República Dominicana"});
			Country.insert({students:"0",name:"Equador"});
			Country.insert({students:"0",name:"Salvador"});
			Country.insert({students:"0",name:"Guiné Equatorial"});
			Country.insert({students:"0",name:"Etiópia"});
			Country.insert({students:"0",name:"Eritreia"});
			Country.insert({students:"0",name:"Estónia"});
			Country.insert({students:"0",name:"Faroé"});
			Country.insert({students:"0",name:"Ilhas Malvinas"});
			Country.insert({students:"0",name:"Geórgia do Sul e Ilhas Sandwich"});
			Country.insert({students:"0",name:"Fiji"});
			Country.insert({students:"0",name:"Finlândia"});
			Country.insert({students:"0",name:"França"});
			Country.insert({students:"0",name:"Polinésia Francesa"});
			Country.insert({students:"0",name:"Territórios Austrais Franceses"});
			Country.insert({students:"0",name:"Jibuti"});
			Country.insert({students:"0",name:"Gabão"});
			Country.insert({students:"0",name:"Geórgia"});
			Country.insert({students:"0",name:"Gâmbia"});
			Country.insert({students:"0",name:"Faixa de Gaza"});
			Country.insert({students:"0",name:"Alemanha"});
			Country.insert({students:"0",name:"Gana"});
			Country.insert({students:"0",name:"Gibraltar"});
			Country.insert({students:"0",name:"Quiribáti"});
			Country.insert({students:"0",name:"Grécia"});
			Country.insert({students:"0",name:"Gronelândia"});
			Country.insert({students:"0",name:"Granada"});
			Country.insert({students:"0",name:"Guame"});
			Country.insert({students:"0",name:"Guatemala"});
			Country.insert({students:"0",name:"Guiné"});
			Country.insert({students:"0",name:"Guiana"});
			Country.insert({students:"0",name:"Haiti"});
			Country.insert({students:"0",name:"Ilhas Heard e McDonald"});
			Country.insert({students:"0",name:"Vaticano"});
			Country.insert({students:"0",name:"Honduras"});
			Country.insert({students:"0",name:"Hong Kong"});
			Country.insert({students:"0",name:"Hungria"});
			Country.insert({students:"0",name:"Islândia"});
			Country.insert({students:"0",name:"Índia"});
			Country.insert({students:"0",name:"Indonésia"});
			Country.insert({students:"0",name:"Irão"});
			Country.insert({students:"0",name:"Iraque"});
			Country.insert({students:"0",name:"Irlanda"});
			Country.insert({students:"0",name:"Israel"});
			Country.insert({students:"0",name:"Itália"});
			Country.insert({students:"0",name:"Costa do Marfim"});
			Country.insert({students:"0",name:"Jamaica"});
			Country.insert({students:"0",name:"Japão"});
			Country.insert({students:"0",name:"Cazaquistão"});
			Country.insert({students:"0",name:"Jordânia"});
			Country.insert({students:"0",name:"Quénia"});
			Country.insert({students:"0",name:"Coréia do Norte"});
			Country.insert({students:"0",name:"Coréia do Sul"});
			Country.insert({students:"0",name:"Kuwait"});
			Country.insert({students:"0",name:"Quirguizistão"});
			Country.insert({students:"0",name:"Laos"});
			Country.insert({students:"0",name:"Líbano"});
			Country.insert({students:"0",name:"Lesoto"});
			Country.insert({students:"0",name:"Letónia"});
			Country.insert({students:"0",name:"Libéria"});
			Country.insert({students:"0",name:"Líbia"});
			Country.insert({students:"0",name:"Listenstaine"});
			Country.insert({students:"0",name:"Lituânia"});
			Country.insert({students:"0",name:"Luxemburgo"});
			Country.insert({students:"0",name:"Macau"});
			Country.insert({students:"0",name:"Madagáscar"});
			Country.insert({students:"0",name:"Malávi"});
			Country.insert({students:"0",name:"Malásia"});
			Country.insert({students:"0",name:"Maldivas"});
			Country.insert({students:"0",name:"Mali"});
			Country.insert({students:"0",name:"Malta"});
			Country.insert({students:"0",name:"Martinique"});
			Country.insert({students:"0",name:"Mauritânia"});
			Country.insert({students:"0",name:"Maurícia"});
			Country.insert({students:"0",name:"México"});
			Country.insert({students:"0",name:"Mónaco"});
			Country.insert({students:"0",name:"Mongólia"});
			Country.insert({students:"0",name:"Moldávia"});
			Country.insert({students:"0",name:"Montenegro"});
			Country.insert({students:"0",name:"Monserrate"});
			Country.insert({students:"0",name:"Marrocos"});
			Country.insert({students:"0",name:"Moçambique"});
			Country.insert({students:"0",name:"Omã"});
			Country.insert({students:"0",name:"Namíbia"});
			Country.insert({students:"0",name:"Nauru"});
			Country.insert({students:"0",name:"Nepal"});
			Country.insert({students:"0",name:"Países Baixos"});
			Country.insert({students:"0",name:"Aruba"});
			Country.insert({students:"0",name:"Nova Caledónia"});
			Country.insert({students:"0",name:"Vanuatu"});
			Country.insert({students:"0",name:"Nova Zelândia"});
			Country.insert({students:"0",name:"Nicarágua"});
			Country.insert({students:"0",name:"Niger"});
			Country.insert({students:"0",name:"Nigéria"});
			Country.insert({students:"0",name:"Niue"});
			Country.insert({students:"0",name:"Ilha Norfolk"});
			Country.insert({students:"0",name:"Noruega"});
			Country.insert({students:"0",name:"Marianas do Norte"});
			Country.insert({students:"0",name:"Micronésia"});
			Country.insert({students:"0",name:"Ilhas Marshall"});
			Country.insert({students:"0",name:"Palau"});
			Country.insert({students:"0",name:"Paquistão"});
			Country.insert({students:"0",name:"Panamá"});
			Country.insert({students:"0",name:"Papua-Nova Guiné"});
			Country.insert({students:"0",name:"Paraguai"});
			Country.insert({students:"0",name:"Peru"});
			Country.insert({students:"0",name:"Filipinas"});
			Country.insert({students:"0",name:"Pitcairn"});
			Country.insert({students:"0",name:"Polónia"});
			Country.insert({students:"0",name:"Portugal"});
			Country.insert({students:"0",name:"Guiné-Bissau"});
			Country.insert({students:"0",name:"Timor Leste"});
			Country.insert({students:"0",name:"Porto Rico"});
			Country.insert({students:"0",name:"Catar"});
			Country.insert({students:"0",name:"Roménia"});
			Country.insert({students:"0",name:"Rússia"});
			Country.insert({students:"0",name:"Ruanda"});
			Country.insert({students:"0",name:"Santa Helena"});
			Country.insert({students:"0",name:"São Cristóvão e Neves"});
			Country.insert({students:"0",name:"Anguila"});
			Country.insert({students:"0",name:"Santa Lúcia"});
			Country.insert({students:"0",name:"São Marinho"});
			Country.insert({students:"0",name:"São Pedro e Miquelon"});
			Country.insert({students:"0",name:"São Vicente e Granadinas"});
			Country.insert({students:"0",name:"São Tomé e Príncipe"});
			Country.insert({students:"0",name:"Arábia Saudita"});
			Country.insert({students:"0",name:"Antilhas Neerlandesas"});
			Country.insert({students:"0",name:"Senegal"});
			Country.insert({students:"0",name:"Serbia"});
			Country.insert({students:"0",name:"Seicheles"});
			Country.insert({students:"0",name:"Serra Leoa"});
			Country.insert({students:"0",name:"Singapura"});
			Country.insert({students:"0",name:"Eslováquia"});
			Country.insert({students:"0",name:"Vietname"});
			Country.insert({students:"0",name:"Eslovénia"});
			Country.insert({students:"0",name:"Somália"});
			Country.insert({students:"0",name:"África do Sul"});
			Country.insert({students:"0",name:"Zimbabué"});
			Country.insert({students:"0",name:"Espanha"});
			Country.insert({students:"0",name:"Sara Ocidental"});
			Country.insert({students:"0",name:"Sudão"});
			Country.insert({students:"0",name:"Suriname"});
			Country.insert({students:"0",name:"Svalbard e Jan Mayen"});
			Country.insert({students:"0",name:"Suazilândia"});
			Country.insert({students:"0",name:"Suécia"});
			Country.insert({students:"0",name:"Suíça"});
			Country.insert({students:"0",name:"Síria"});
			Country.insert({students:"0",name:"Tajiquistão"});
			Country.insert({students:"0",name:"Tailândia"});
			Country.insert({students:"0",name:"Togo"});
			Country.insert({students:"0",name:"Tokelau"});
			Country.insert({students:"0",name:"Guiana Francesa"});
			Country.insert({students:"0",name:"Tonga"});
			Country.insert({students:"0",name:"Trindade e Tobago"});
			Country.insert({students:"0",name:"Emiratos Árabes Unidos"});
			Country.insert({students:"0",name:"Tunísia"});
			Country.insert({students:"0",name:"Turquia"});
			Country.insert({students:"0",name:"Turquemenistão"});
			Country.insert({students:"0",name:"Ilhas Turcas e Caicos"});
			Country.insert({students:"0",name:"Tuvalu"});
			Country.insert({students:"0",name:"Uganda"});
			Country.insert({students:"0",name:"Ucrânia"});
			Country.insert({students:"0",name:"Macedónia"});
			Country.insert({students:"0",name:"Egíto"});
			Country.insert({students:"0",name:"Reino Unido"});
			Country.insert({students:"0",name:"Guernsey"});
			Country.insert({students:"0",name:"Jersey"});
			Country.insert({students:"0",name:"Ilha de Man"});
			Country.insert({students:"0",name:"Tanzânia"});
			Country.insert({students:"0",name:"Estados Unidos"});
			Country.insert({students:"0",name:"Ilhas Virgens"});
			Country.insert({students:"0",name:"Burquina Faso"});
			Country.insert({students:"0",name:"Uruguai"});
			Country.insert({students:"0",name:"Usbequistão"});
			Country.insert({students:"0",name:"Venezuela"});
			Country.insert({students:"0",name:"Wallis e Futuna"});
			Country.insert({students:"0",name:"Samoa Americana"});
			Country.insert({students:"0",name:"Iémen"});
			Country.insert({students:"0",name:"Zâmbia"});
		}
	});
});
